import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/common/Header";
import FormInfo from "../components/common/FormInfo";
export default function Home() {
  return (
    <>
      <Head>
        <title>AuthenticMax®</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main className="h-[100vh] px-[20px]">
        <FormInfo />
      </main>
    </>
  );
}
